//actions
export const FETCH_AUDIENCE_REQUEST = 'FETCH_AUDIENCE_REQUEST'
export const FETCH_AUDIENCE_SUCCESS = 'FETCH_AUDIENCE_SUCCESS'
export const FETCH_AUDIENCE_ERROR = 'FETCH_AUDIENCE_ERROR'


export const ADD_AUDIENCE_REQUEST = "ADD_AUDIENCE_REQUEST"
export const ADD_AUDIENCE_SUCCESS = "ADD_AUDIENCE_SUCCESS"
export const ADD_AUDIENCE_ERROR = "ADD_AUDIENCE_ERROR"

export const BOOK_TICKET_REQUEST = "BOOK_TICKET_REQUEST"
export const BOOK_TICKET_SUCCESS = "BOOK_TICKET_SUCCESS"
export const BOOK_TICKET_ERROR = "BOOK_TICKET_ERROR"


// export const UPDATE_GROUNDS_REQUEST = "UPDATE_GROUNDS_REQUEST"
// export const UPDATE_GROUNDS_SUCCESS = "UPDATE_GROUNDS_SUCCESS"
// export const UPDATE_GROUNDS_ERROR = "UPDATE_GROUNDS_ERROR"

// export const DELETE_GROUNDS_REQUEST = "DELETE_GROUNDS_REQUEST"
// export const DELETE_GROUNDS_SUCCESS = "DELETE_GROUNDS_SUCCESS"
// export const DELETE_GROUNDS_ERROR = "DELETE_GROUNDS_ERROR"
