// actions
export const FETCH_GROUNDS_REQUEST = 'FETCH_GROUNDS_REQUEST'
export const FETCH_GROUNDS_SUCCESS = 'FETCH_GROUNDS_SUCCESS'
export const FETCH_GROUNDS_ERROR = 'FETCH_GROUNDS_ERROR'


export const ADD_GROUNDS_REQUEST = "ADD_GROUNDS_REQUEST"
export const ADD_GROUND_SUCCESS = "ADD_GROUNDS_SUCCESS"
export const ADD_GROUNDS_ERROR = "ADD_GROUNDS_ERROR"


export const UPDATE_GROUNDS_REQUEST = "UPDATE_GROUNDS_REQUEST"
export const UPDATE_GROUNDS_SUCCESS = "UPDATE_GROUNDS_SUCCESS"
export const UPDATE_GROUNDS_ERROR = "UPDATE_GROUNDS_ERROR"

export const DELETE_GROUNDS_REQUEST = "DELETE_GROUNDS_REQUEST"
export const DELETE_GROUNDS_SUCCESS = "DELETE_GROUNDS_SUCCESS"
export const DELETE_GROUNDS_ERROR = "DELETE_GROUNDS_ERROR"