export const FETCH_MATCH_REQUEST = "FETCH_MATCH_REQUEST"
export const FETCH_MATCH_SUCCESS = "FETCH_MATCH_SUCCESS"
export const FETCH_MATCH_FAIL = "FETCH_MATCH_FAIL"


export const ADD_MATCH_REQUEST = "ADD_MATCH_REQUEST";
export const ADD_MATCH_SUCCESS = "ADD_MATCH_SUCCESS";
export const ADD_MATCH_ERROR = "ADD_MATCH_ERROR";

export const CANCEL_MATCH_REQUEST = "CANCEL_MATCH_REQUEST";
export const CANCEL_MATCH_SUCCESS = "CANCEL_MATCH_SUCCESS";
export const CANCEL_MATCH_ERROR = "CANCEL_MATCH_ERROR";