export const FETCH_ORGANISER_REQUEST = 'FETCH_ORGANISER_REQUEST'
export const FETCH_ORGANISER_SUCCESS = 'FETCH_ORGANISER_SUCCESS'
export const FETCH_ORGANISER_ERROR = 'FETCH_ORGANISER_ERROR'


export const ADD_ORGANISER_REQUEST = "ADD_ORGANISER_REQUEST"
export const ADD_ORGANISER_SUCCESS = "ADD_ORGANISER_SUCCESS"
export const ADD_ORGANISER_ERROR = "ADD_ORGANISER_ERROR"


export const UPDATE_ORGANISER_REQUEST = "UPDATE_ORGANISER_REQUEST"
export const UPDATE_ORGANISER_SUCCESS = "UPDATE_ORGANISER_SUCCESS"
export const UPDATE_ORGANISER_ERROR = "UPDATE_ORGANISER_ERROR"

export const FETCH_ORGANISER_TOURNAMENTS_REQUEST = 'FETCH_ORGANISER_TOURNAMENTS_REQUEST'
export const FETCH_ORGANISER_TOURNAMENTS_SUCCESS = 'FETCH_ORGANISER_TOURNAMENTS_SUCCESS'
export const FETCH_ORGANISER_TOURNAMENTS_ERROR = 'FETCH_ORGANISER_TOURNAMENTS_ERROR'

export const FETCH_ORGANISERBYID_REQUEST = 'FETCH_ORGANISERBYID_REQUEST'
export const FETCH_ORGANISERBYID_SUCCESS = 'FETCH_ORGANISERBYID_SUCCESS'
export const FETCH_ORGANISERBYID_ERROR = 'FETCH_ORGANISERBYID_ERROR'

export const PRIZE_MONEY_REQUEST = 'PRIZE_MONEY_REQUEST'
export const PRIZE_MONEY_SUCCESS = 'PRIZE_MONEY_SUCCESS'
export const PRIZE_MONEY_ERROR = 'PRIZE_MONEY_ERROR'