// actions
export const FETCH_OWNERS_REQUEST = 'FETCH_OWNERS_REQUEST'
export const FETCH_OWNERS_SUCCESS = 'FETCH_OWNERS_SUCCESS'
export const FETCH_OWNERS_ERROR = 'FETCH_OWNERS_ERROR'


export const ADD_OWNERS_REQUEST = "ADD_OWNERS_REQUEST"
export const ADD_OWNER_SUCCESS = "ADD_OWNERS_SUCCESS"
export const ADD_OWNERS_ERROR = "ADD_OWNERS_ERROR"


export const UPDATE_OWNERS_REQUEST = "UPDATE_OWNERS_REQUEST"
export const UPDATE_OWNERS_SUCCESS = "UPDATE_OWNERS_SUCCESS"
export const UPDATE_OWNERS_ERROR = "UPDATE_OWNERS_ERROR"

export const DELETE_OWNERS_REQUEST = "DELETE_OWNERS_REQUEST"
export const DELETE_OWNERS_SUCCESS = "DELETE_OWNERS_SUCCESS"
export const DELETE_OWNERS_ERROR = "DELETE_OWNERS_ERROR"

export const FETCH_OWNERBYID_REQUEST = 'FETCH_OWNERBYID_REQUEST'
export const FETCH_OWNERBYID_SUCCESS = 'FETCH_OWNERBYID_SUCCESS'
export const FETCH_OWNERBYID_ERROR = 'FETCH_OWNERBYID_ERROR'

export const PAY_SALARY_REQUEST = 'PAY_SALARY_REQUEST'
export const PAY_SALARY_SUCCESS = 'PAY_SALARY_SUCCESS'
export const PAY_SALARY_ERROR = 'PAY_SALARY_ERROR'