export const FETCH_PLAYERS_REQUEST = "FETCH_PLAYERS_REQUEST";
export const FETCH_PLAYERS_SUCCESS = "FETCH_PLAYERS_SUCCESS";
export const FETCH_PLAYERS_FAILURE = "FETCH_PLAYERS_FAILURE";
export const ADD_PLAYER_REQUEST = "ADD_PLAYER_REQUEST";
export const UPDATE_PLAYER_REQUEST = "UPDATE_PLAYER_REQUEST";
export const DELETE_PLAYER_REQUEST = "DELETE_PLAYER_REQUEST";
export const FETCH_PLAYERBYID_REQUEST = "FETCH_PLAYERBYID_REQUEST";