// actions
export const FETCH_TEAMS_REQUEST = 'FETCH_TEAMS_REQUEST'
export const FETCH_TEAMS_SUCCESS = 'FETCH_TEAMS_SUCCESS'
export const FETCH_TEAMS_ERROR = 'FETCH_TEAMS_ERROR'

export const ADD_TEAMS_REQUEST = "ADD_TEAMS_REQUEST"
export const ADD_TEAMS_SUCCESS = "ADD_TEAMS_SUCCESS"
export const ADD_TEAMS_ERROR = "ADD_TEAMS_ERROR"

export const UPDATE_TEAMS_REQUEST = "UPDATE_TEAMS_REQUEST"
export const UPDATE_TEAMS_SUCCESS = "UPDATE_TEAMS_SUCCESS"
export const UPDATE_TEAMS_ERROR = "UPDATE_TEAMS_ERROR"

export const DELETE_TEAMS_REQUEST = "DELETE_TEAMS_REQUEST"
export const DELETE_TEAMS_SUCCESS = "DELETE_TEAMS_SUCCESS"
export const DELETE_TEAMS_ERROR = "DELETE_TEAMS_ERROR"

export const FETCH_TEAMBYID_REQUEST = 'FETCH_TEAMBYID_REQUEST'
export const FETCH_TEAMBYID_SUCCESS = 'FETCH_TEAMBYID_SUCCESS'
export const FETCH_TEAMBYID_ERROR = 'FETCH_TEAMBYID_ERROR'

export const FETCH_TEAM_PLAYERS_REQUEST = 'FETCH_TEAM_PLAYERS_REQUEST'
export const FETCH_TEAM_PLAYERS_SUCCESS = 'FETCH_TEAM_PLAYERS_SUCCESS'
export const FETCH_TEAM_PLAYERS_ERROR = 'FETCH_TEAM_PLAYERS_ERROR'