export const FETCH_TOURNAMENT_REQUEST = 'FETCH_TOURNAMENT_REQUEST'
export const FETCH_TOURNAMENT_SUCCESS = 'FETCH_TOURNAMENT_SUCCESS'
export const FETCH_TOURNAMENT_ERROR = 'FETCH_TOURNAMENT_ERROR'

export const FETCH_TOURNAMENTBYID_REQUEST = 'FETCH_TOURNAMENTBYID_REQUEST'
export const FETCH_TOURNAMENTBYID_SUCCESS = 'FETCH_TOURNAMENTBYID_SUCCESS'
export const FETCH_TOURNAMENTBYID_ERROR = 'FETCH_TOURNAMENTBYID_ERROR'

export const ADD_TOURNAMENT_REQUEST = "ADD_TOURNAMENT_REQUEST"
export const ADD_TOURNAMENT_SUCCESS = "ADD_TOURNAMENT_SUCCESS"
export const ADD_TOURNAMENT_ERROR = "ADD_TOURNAMENT_ERROR"

export const UPDATE_TOURNAMENT_REQUEST = "UPDATE_TOURNAMENT_REQUEST"
export const UPDATE_TOURNAMENT_SUCCESS = "UPDATE_TOURNAMENT_SUCCESS"
export const UPDATE_TOURNAMENT_ERROR = "UPDATE_TOURNAMENT_ERROR"